added dialog

diff --git a/surserver-media_permissions b/surserver-media_permissions
--- a/surserver-media_permissions
+++ b/surserver-media_permissions
@@ -19,6 +19,62 @@ fix_permissions () {
 	done
 }
 
+custom_entry () {
+	path=$(dialog \
+		--title "SurServer Media Permissions" \
+		--inputbox "Enter full path: \n \
+		( ex.: /full/path/to/dir/ )" 10 40 \
+		3>&1 1>&2 2>&3 3>&-)
+	clear
+	if [ "$path" == "" ]; then echo -e "No path, aborting..."; exit 1; fi
+	user=$(dialog \
+		--title "SurServer Media Permissions" \
+		--inputbox "Enter user: \n \
+		( ex.: dietpi or 1000 )" 10 40 \
+		3>&1 1>&2 2>&3 3>&-)
+	clear
+	if [ "$user" == "" ]; then echo -e "No user, aborting..."; exit 1; fi
+	group=$(dialog \
+		--title "SurServer Media Permissions" \
+		--inputbox "Enter group: \n \
+		( ex.: dietpi or 1000 )" 10 40 \
+		3>&1 1>&2 2>&3 3>&-)
+	clear
+	if [ "$group" == "" ]; then echo -e "No group, aborting..."; exit 1; fi
+	fix_permissions $path $user $group
+}
+
+main_menu () {
+	checklist=(dialog --separate-output --checklist "Select options:" 22 76 16)
+	options=(1 "Audio $AUDIO_OWNER:$GROUP" off    
+			2 "Series $SERIES_OWNER:$GROUP" off
+			3 "Movies $MOVIES_OWNER:$GROUP" off
+			4 "Concerts $CONCERTS_OWNER:$GROUP" off
+			5 "Custom" off)
+	choices=$("${checklist[@]}" "${options[@]}" 2>&1 >/dev/tty)
+	clear
+	for choice in $choices
+	do
+		case $choice in
+			1)
+				fix_permissions $AUDIOROOT $AUDIO_OWNER $GROUP
+				;;
+			2)
+				fix_permissions $SERIESROOT $SERIES_OWNER $GROUP
+				;;
+			3)
+				fix_permissions $MOVIESROOT $MOVIES_OWNER $GROUP
+				;;
+			4)
+				fix_permissions $CONCERTSROOT $CONCERTS_OWNER $GROUP
+				;;
+			5)
+				custom_entry
+				;;
+		esac
+	done
+}
+
 ## STATUP OPTIONS
 if [ "$1" = '-a' ] || [ "$1" = '--audio' ]; then
 	fix_permissions $AUDIOROOT $AUDIO_OWNER $GROUP
@@ -32,7 +88,7 @@ elif [ "$1" = '-m' ] || [ "$1" = '--movies' ]; then
 elif [ "$1" = '-c' ] || [ "$1" = '--concerts' ]; then
 	fix_permissions $CONCERTSROOT $CONCERTS_OWNER $GROUP
 
-elif [ "$1" = '-s' ] || [ "$1" = '--set' ]; then
+elif [ "$1" = '-t' ] || [ "$1" = '--target' ]; then
 	fix_permissions $2 $3 $4
 
 elif [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
@@ -44,9 +100,9 @@ elif [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
 	echo -e " -s [--series]		 -> Fix all series permissions"
 	echo -e " -m [--movies]		 -> Fix all movies permissions"
 	echo -e " -c [--concerts]	 -> Fix all concerts permissions"
-	echo -e "${WARN} -s [--set]		 -> Manually enter desired settings."
-	echo -e " Usage: surserver-media_permissions [-s] [--set] /dir/path owner group${NC}"
+	echo -e "${WARN} -s [--target]		 -> Manually enter desired settings."
+	echo -e " Usage: surserver-media_permissions [-s] [--target] /dir/path user group${NC}"
 	echo -e " -h [--help]		 -> Shows this screen."
 else
-	echo -e "No valid arguement.\nPlease use surserver-media_permission --help"
+	main_menu;
 fi
