added launcher return

diff --git a/surserver-media_permissions b/surserver-media_permissions
--- a/surserver-media_permissions
+++ b/surserver-media_permissions
@@ -26,26 +26,29 @@ custom_entry () {
 		( ex.: /full/path/to/dir/ )" 10 40 \
 		3>&1 1>&2 2>&3 3>&-)
 	clear
-	if [ "$path" == "" ]; then echo -e "No path, aborting..."; exit 1; fi
+	if [ "$path" == "" ]; then echo -e "${ERROR}No path, aborting...${NC}"; sleep 2;
+		clear && eval surserver-launcher; exit 1; fi
 	user=$(dialog \
 		--title "SurServer Media Permissions" \
 		--inputbox "Enter user: \n \
 		( ex.: dietpi or 1000 )" 10 40 \
 		3>&1 1>&2 2>&3 3>&-)
 	clear
-	if [ "$user" == "" ]; then echo -e "No user, aborting..."; exit 1; fi
+	if [ "$user" == "" ]; then echo -e "${ERROR}No user, aborting...${NC}"; sleep 2;
+		clear && eval surserver-launcher; exit 1; fi
 	group=$(dialog \
 		--title "SurServer Media Permissions" \
 		--inputbox "Enter group: \n \
 		( ex.: dietpi or 1000 )" 10 40 \
 		3>&1 1>&2 2>&3 3>&-)
 	clear
-	if [ "$group" == "" ]; then echo -e "No group, aborting..."; exit 1; fi
+	if [ "$group" == "" ]; then echo -e "${ERROR}No group, aborting...${NC}"; sleep 2;
+		clear && eval surserver-launcher; exit 1; fi
 	fix_permissions $path $user $group
 }
 
 main_menu () {
-	checklist=(dialog --separate-output --checklist "Select options:" 22 76 16)
+	checklist=(dialog --separate-output --checklist "Select option(s) with spacebar:" 22 76 16)
 	options=(1 "Audio $AUDIO_OWNER:$GROUP" off    
 			2 "Series $SERIES_OWNER:$GROUP" off
 			3 "Movies $MOVIES_OWNER:$GROUP" off
@@ -73,6 +76,8 @@ main_menu () {
 				;;
 		esac
 	done
+	## go back to launcher if nothins is selected
+	clear && eval surserver-launcher; exit 1;
 }
 
 ## STATUP OPTIONS
diff --git a/surserver-media_share b/surserver-media_share
--- a/surserver-media_share
+++ b/surserver-media_share
@@ -9,7 +9,7 @@
 if [ -f /home/dietpi/bin/.env ]; then
     . /home/dietpi/bin/.env
 else
-    echo -e "${ERROR}FATAL ERROR: .env not found.${NC}\nAborting..."
+    echo -e "${ERROR}FATAL ERROR: .env not found.${NC}\nAborting...";
     exit 1;
 fi
 
@@ -58,7 +58,8 @@ create_checklist () {
 			source+=$(get_selections $1.folder_content.txt $choice $1);
 		done
 	else
-		echo -e "${ERROR}No selection, aborting...${NC}"; exit 1;
+		echo -e "${ERROR}No selection, aborting...${NC}"; sleep 2;
+		clear && eval surserver-launcher; exit 1;
 	fi
 	
 	## set destination (user input dialog)
@@ -73,7 +74,8 @@ create_checklist () {
 	if [ "$dest" != "" ]; then
 		copy_media $source $dest;
 	else
-		echo -e "${ERROR}No destination, aborting...${NC}"; exit 1;
+		echo -e "${ERROR}No destination, aborting...${NC}"; sleep 2;
+		clear && eval surserver-launcher; exit 1;
 	fi
 }
 
@@ -90,8 +92,7 @@ main_menu () {
 
 	## Exit on Quit or Cancel || Execute chosen script.
 	if [ $root_dir = 'Quit' ] || [ $? -ne 1 ]; then
-		echo -e 'Exiting...'
-		clear && exit 1;
+		clear && eval surserver-launcher; exit 1;
 	else
 		##TODO: check if folder exists 1st
 		create_checklist $root_dir;
