minor tweaks and comments, added abort timers

diff --git a/surserver-converter_mp3 b/surserver-converter_mp3
--- a/surserver-converter_mp3
+++ b/surserver-converter_mp3
@@ -13,8 +13,9 @@
 if [ -f /home/dietpi/bin/.env ]; then
     . /home/dietpi/bin/.env
 else
-    echo -e "${ERROR}FATAL ERROR: .env not found.${NC}\nAborting..."
-	exit 1;
+    echo -e "FATAL ERROR: .env not found.$\n
+	Use surserver-setup_enviroment to create one.\nAborting...";
+    exit 1;
 fi
 
 ## AUTOMODE DEFAULT FLAGS (--auto)
@@ -133,11 +134,8 @@ execute_tasks (){
 	echo -e "________________________________________________\n"
 	echo -e "${OK}Starting...${NC}"
 	echo -e "Press ${WARN}"Control + C"${NC} to abort.\n"
-	for (( i=3; i>0; i--)); do
-	sleep 1 &
-	printf "            $i \r"
-	wait
-	done
+	for (( i=3; i>0; i--)); do sleep 1 & printf "            $i \r"; wait; done
+	
 	for format in "${FORMAT_ARRAY[@]}"; do
 		echo -e "${OK}Starting ${WARN}$format${OK} conversion...${NC}"
 		find -name "*.${format}" -exec bash -c 'ffmpeg -i "{}" -y -acodec libmp3lame -ab '${BITRATE}' "${0/.'${format}'}.mp3"' {} \;
diff --git a/surserver-media_backup b/surserver-media_backup
--- a/surserver-media_backup
+++ b/surserver-media_backup
@@ -9,8 +9,9 @@
 if [ -f /home/dietpi/bin/.env ]; then
     . /home/dietpi/bin/.env
 else
-    echo -e "${ERROR}FATAL ERROR: .env not found.${NC}\nAborting..."
-    exit 1;  ## call setup env later
+    echo -e "FATAL ERROR: .env not found.$\n
+	Use surserver-setup_enviroment to create one.\nAborting...";
+    exit 1;
 fi
 
 #todo:  log stuff
@@ -34,8 +35,10 @@ execute_backup (){
         echo -e "Aborting..."
         exit 1;
     }
+	echo -e "Press ${WARN}"Control + C"${NC} to abort.\n"
+	for (( i=3; i>0; i--)); do sleep 1 & printf "            $i \r"; wait; done
     #start backup sync
-    rsync -avzp "$1"* "$2" --delete
+    rsync -avzP "$1"* "$2" --delete
     echo -e "\nBackup complete."
 }
 
diff --git a/surserver-media_permissions b/surserver-media_permissions
--- a/surserver-media_permissions
+++ b/surserver-media_permissions
@@ -9,8 +9,9 @@
 if [ -f /home/dietpi/bin/.env ]; then
     . /home/dietpi/bin/.env
 else
-    echo -e "${ERROR}FATAL ERROR: .env not found.${NC}\nAborting..."
-	exit 1;
+    echo -e "FATAL ERROR: .env not found.$\n
+	Use surserver-setup_enviroment to create one.\nAborting...";
+    exit 1;
 fi
 
 ## DO STUFF
diff --git a/surserver-setup_enviroment b/surserver-setup_enviroment
--- a/surserver-setup_enviroment
+++ b/surserver-setup_enviroment
@@ -16,7 +16,7 @@ KEYS=(AUDIOROOT AUDIOBACKUP AUDIOJUNK VIDEOSROOT VIDEOSBACKUP VIDEOSJUNK SERIESR
 ## edit or create new env file
 if [ -f $ENV_FILE ]; then . $ENV_FILE;
 else cp $TEMPLATE $ENV_FILE && . $ENV_FILE || { 
-    echo -e "${ERROR}Could not create env file.\nAborted."; exit 1;};
+    echo -e "FATAL ERROR: Could not create env file.\nAborted."; exit 1;};
 fi
 
 #folders setup, user/groups setup
@@ -55,11 +55,16 @@ main_form () {
     while read -r line; do
         sed -i -e '/'"${KEYS[((i++))]}"'=/ s|=.*|='"\"${line}\""'|' $ENV_FILE
     done <<< "${filled_form}"
+
+    # return to launcher
+    clear && eval surserver-launcher; exit 1;
 }
 
 if [ "$1" = '-t' ] || [ "$1" = '--template' ]; then
+    if [ -f $ENV_FILE ]; then echo -e "$ENV_FILE exists!!!\nManually delete it if you want to reset to a template."; exit 1; fi
     echo -e "Creating new env file from template at $ENV_FILE"
-    cp $TEMPLATE $ENV_FILE && . $ENV_FILE || { echo -e "${ERROR}Could not create env file.\nAborted."; exit 1; }
+    cp $TEMPLATE $ENV_FILE || { echo -e "Could not create $ENV_FILE.\Maybe check permissions...\nAborted."; exit 1; }
+
 elif [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
     echo -e "${OK}SurServer Setup Enviroment${NC}"
     echo -e "Create new .env file or update enviroment variables in .env file"
